server.log.file.level=info
server.log.console.level=error

wifiin.redis.life.time=3600

wifiin.message.key=J22472m312506083
wifiin.message.salt=41EAbXqlospdtruz
wifiin.message.iv=156782572202746I

spring.datasource.mysql.jdbcUrl=jdbc\:mysql\://127.0.0.1\:28067/speedin?autoReconnect\=true&useUnicode\=true&characterEncoding\=utf-8&cachePrepStmts\=true&zeroDateTimeBehavior\=convertToNull
spring.datasource.mysql.username=wifiin
spring.datasource.mysql.password=OtbqAzzsV20710
spring.datasource.mysql.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.mysql.readOnly=false
spring.datasource.mysql.autoCommit=true
spring.datasource.mysql.initializationFailTimeout=1000
spring.datasource.mysql.connectionTestQuery=select 1
spring.datasource.mysql.connectionInitSql=select 1
spring.datasource.mysql.connectionTimeout=1000
spring.datasource.mysql.idleTimeout=0
spring.datasource.mysql.maxLifetime=119000
spring.datasource.mysql.leakDetectionThreshold=60000
spring.datasource.mysql.maximumPoolSize=200
spring.datasource.mysql.minimumIdle=10
spring.datasource.mysql.validationTimeout=1000
spring.redis.host=127.0.0.1:36379
spring.redis.password=_834smMim7
spring.redis.timeout=10000
spring.redis.max-total=1000
spring.redis.max-idle=500
spring.redis.max-wait-millis=10000
spring.redis.min-idle=10
spring.redis.test-on-borrow=true
spring.redis.test-on-return=false
spring.redis.test-while-idle=true
spring.redis.to-throw-on-error=true

dubbo.container=log4j,spring
dubbo.application.logger=slf4j
dubbo.application.name=speedin-mvc
dubbo.registry.file=/data/www/wifiin/wsapp/speedin-server-core/speedin-mvc.properties
dubbo.application.owner=

dubbo.registry.client=curator
dubbo.registry.address=zookeeper://172.16.0.31:2181?backup=172.16.0.32:2181,172.16.0.33:2181

dubbo.monitor.protocol=registry
dubbo.protocol.name=spring.dubbo
dubbo.protocol.port=20000
dubbo.protocol.transporter=netty4
dubbo.protocol.serialization=fst
#dubbo.protocol.serialization=kryo
dubbo.protocol.charset=UTF-8
dubbo.protocol.accepts=1000

dubbo.consumer.filter=consumerLog
dubbo.consumer.check=false
dubbo.consumer.timeout=30000

dubbo.service.loadbalance=roundrobin
dubbo.reference.version=@wifiin.server.platform.version@

dubbo.scan.base-packages=com.wifiin.invpn

# Chat Memory Configuration
spring.ai.chat.memory.sliding-window-size=20
